// <auto-generated />
using System;
using AFH.Acs.Recorder.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFH.Acs.Recorder.Infrastructure.Migrations.V2
{
    [DbContext(typeof(MeetingDbContext))]
    [Migration("20251204154340_StagingSQLConfigManagement_v1.0.3")]
    partial class StagingSQLConfigManagement_v103
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.AdviserEntity", b =>
                {
                    b.Property<string>("AdviserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ADVISER_ID");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE_FLAG");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FULL_NAME");

                    b.Property<bool>("LeadTechFlag")
                        .HasColumnType("bit")
                        .HasColumnName("LEAD_TECH_FLAG");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("REGION");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT_UTC");

                    b.HasKey("AdviserId")
                        .HasName("PK_ADVISERS");

                    b.ToTable("ADVISERS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.ApplicationLogsEntity", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LOG_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CORRELATION_ID");

                    b.Property<string>("EventType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EVENT_TYPE");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EXCEPTION_MESSAGE");

                    b.Property<string>("ExceptionStack")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EXCEPTION_STACK");

                    b.Property<string>("FunctionName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("FUNCTION_NAME");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("LOG_LEVEL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PAYLOAD_JSON");

                    b.Property<string>("RequestId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("REQUEST_ID");

                    b.Property<DateTime>("TimestampUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP_UTC")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("LogId")
                        .HasName("PK_APPLICATION_LOGS");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("TimestampUtc");

                    b.ToTable("APPLICATION_LOGS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.AtrTemplateEntity", b =>
                {
                    b.Property<string>("AtrId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ATR_ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("KeypointHeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KEYPOINT_HEADER");

                    b.Property<string>("ParagraphText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PARAGRAPH_TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RISK_LEVEL");

                    b.HasKey("AtrId")
                        .HasName("PK_ATR_TEMPLATES");

                    b.ToTable("ATR_TEMPLATES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.ChecklistItemTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TEMPLATE_ID");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ITEM_ID");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("DISPLAY_ORDER");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DISPLAY_TEXT");

                    b.HasKey("TemplateId", "ItemId");

                    b.ToTable("CHECKLIST_ITEM_TEMPLATES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.ChecklistTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TEMPLATE_ID");

                    b.Property<bool>("ActiveFlag")
                        .HasColumnType("bit")
                        .HasColumnName("ACTIVE_FLAG");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MEETING_TYPE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("TemplateId")
                        .HasName("PK_CHECKLIST_TEMPLATES");

                    b.ToTable("CHECKLIST_TEMPLATES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.LeadEntity", b =>
                {
                    b.Property<string>("LeadId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LEAD_ID");

                    b.Property<string>("ClientEmail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENT_EMAIL");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENT_ID");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENT_NAME");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SOURCE_SYSTEM");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT_UTC");

                    b.HasKey("LeadId")
                        .HasName("PK_LEADS");

                    b.ToTable("LEADS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingAtrAnalysisEntity", b =>
                {
                    b.Property<string>("MeetingId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("ClientAtrText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENT_ATR_TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("MatchedTemplateIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MATCHED_TEMPLATE_IDS_JSON");

                    b.Property<string>("MissingKeypointsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MISSING_KEYPOINTS_JSON");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTES");

                    b.HasKey("MeetingId");

                    b.ToTable("MEETING_ATR_ANALYSES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingAttendeeEntity", b =>
                {
                    b.Property<string>("MeetingId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("ResponseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RESPONSE_STATUS");

                    b.Property<DateTime?>("ResponseTimeUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RESPONSE_TIME_UTC");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ROLE");

                    b.HasKey("MeetingId", "Email");

                    b.ToTable("MEETING_ATTENDEES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingChecklistItemEntity", b =>
                {
                    b.Property<string>("MeetingId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ITEM_ID");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("COMPLETED_AT_UTC");

                    b.Property<string>("DisplayText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DISPLAY_TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("IS_COMPLETED");

                    b.HasKey("MeetingId", "ItemId");

                    b.ToTable("MEETING_CHECKLIST_ITEMS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", b =>
                {
                    b.Property<string>("MeetingId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ADVISER_ID");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CLIENT_EMAIL");

                    b.Property<DateTime?>("ConsentTimestampUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CONSENT_TIMESTAMP_UTC");

                    b.Property<bool>("ConsentToRecording")
                        .HasColumnType("bit")
                        .HasColumnName("CONSENT_TO_RECORDING");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("END_UTC");

                    b.Property<string>("GraphEventId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GRAPH_EVENT_ID");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("LEAD_ID");

                    b.Property<string>("MeetingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MEETING_TYPE");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("START_UTC");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT_UTC");

                    b.HasKey("MeetingId")
                        .HasName("PK_MEETINGS");

                    b.HasIndex("AdviserId")
                        .HasDatabaseName("IX_MEETINGS_ADVISER_ID");

                    b.HasIndex("LeadId")
                        .HasDatabaseName("IX_MEETINGS_LEAD_ID");

                    b.ToTable("MEETINGS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingNoteEntity", b =>
                {
                    b.Property<string>("NoteId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NOTE_ID");

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ADVISER_ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("MeetingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NOTE_TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT_UTC");

                    b.HasKey("NoteId")
                        .HasName("PK_MEETING_NOTES");

                    b.HasIndex("AdviserId")
                        .HasDatabaseName("IX_MEETING_NOTES_ADVISER_ID");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("IX_MEETING_NOTES_MEETING_ID");

                    b.ToTable("MEETING_NOTES");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingRecordingEntity", b =>
                {
                    b.Property<string>("RecordingId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RECORDING_ID");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BLOB_NAME");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BLOB_URL");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("DURATION_SECONDS");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("MeetingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<DateTime?>("RecordingEndUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RECORDING_END_UTC");

                    b.Property<DateTime>("RecordingStartUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("RECORDING_START_UTC");

                    b.HasKey("RecordingId")
                        .HasName("PK_MEETING_RECORDINGS");

                    b.HasIndex("MeetingId")
                        .HasDatabaseName("IX_MEETING_RECORDINGS_MEETING_ID");

                    b.ToTable("MEETING_RECORDINGS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingTranscriptionEntity", b =>
                {
                    b.Property<string>("TranscriptionId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TRANSCRIPTION_ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FULL_TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LANGUAGE");

                    b.Property<string>("MeetingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("MEETING_ID");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RAW_JSON");

                    b.Property<string>("RecordingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("RECORDING_ID");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUMMARY_TEXT");

                    b.HasKey("TranscriptionId")
                        .HasName("PK_MEETING_TRANSCRIPTIONS");

                    b.HasIndex("MeetingId")
                        .IsUnique()
                        .HasDatabaseName("IX_MEETING_TRANSCRIPTIONS_MEETING_ID");

                    b.HasIndex("RecordingId")
                        .HasDatabaseName("IX_MEETING_TRANSCRIPTIONS_RECORDING_ID");

                    b.ToTable("MEETING_TRANSCRIPTIONS");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.ChecklistItemTemplateEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.ChecklistTemplateEntity", "Template")
                        .WithMany("Items")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CHECKLIST_ITEM_TEMPLATES_CHECKLIST_TEMPLATES_TEMPLATE_ID");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingAtrAnalysisEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithOne("AtrAnalysis")
                        .HasForeignKey("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingAtrAnalysisEntity", "MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_ATR_ANALYSES_MEETINGS_MEETING_ID");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingAttendeeEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany("Attendees")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_ATTENDEES_MEETINGS_MEETING_ID");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingChecklistItemEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_CHECKLIST_ITEMS_MEETINGS_MEETING_ID");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.AdviserEntity", "Adviser")
                        .WithMany("Meetings")
                        .HasForeignKey("AdviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETINGS_ADVISERS_ADVISER_ID");

                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.LeadEntity", "Lead")
                        .WithMany("Meetings")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETINGS_LEADS_LEAD_ID");

                    b.Navigation("Adviser");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingNoteEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.AdviserEntity", "Adviser")
                        .WithMany()
                        .HasForeignKey("AdviserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_NOTES_ADVISERS_ADVISER_ID");

                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany()
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_NOTES_MEETINGS_MEETING_ID");

                    b.Navigation("Adviser");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingRecordingEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithMany("Recordings")
                        .HasForeignKey("MeetingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_RECORDINGS_MEETINGS_MEETING_ID");

                    b.Navigation("Meeting");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingTranscriptionEntity", b =>
                {
                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", "Meeting")
                        .WithOne("Transcription")
                        .HasForeignKey("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingTranscriptionEntity", "MeetingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_TRANSCRIPTIONS_MEETINGS_MEETING_ID");

                    b.HasOne("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingRecordingEntity", "Recording")
                        .WithMany()
                        .HasForeignKey("RecordingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MEETING_TRANSCRIPTIONS_MEETING_RECORDINGS_RECORDING_ID");

                    b.Navigation("Meeting");

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.AdviserEntity", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.ChecklistTemplateEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.LeadEntity", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("AFH.Acs.Recorder.Infrastructure.Data.Entities.MeetingEntity", b =>
                {
                    b.Navigation("AtrAnalysis");

                    b.Navigation("Attendees");

                    b.Navigation("Recordings");

                    b.Navigation("Transcription");
                });
#pragma warning restore 612, 618
        }
    }
}
