<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- Infrastructure depends on Application + Domain (NOT the other way around) -->
    <ProjectReference Include="..\AFH.Booking.Application\AFH.Booking.Application.csproj" />
    <ProjectReference Include="..\AFH.Booking.Domain\AFH.Booking.Domain.csproj" />
    <ProjectReference Include="..\AFH.Booking.Contract\AFH.Booking.Contract.csproj" />
    <ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors.Email\AFH.Common.Errors.Email.csproj" />
    <ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors.EntityFramework\AFH.Common.Errors.EntityFramework.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- EF Core -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.ApplicationInsights" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.5" />

    <!-- Options + DI + Http -->
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.5" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.5" />


	
  </ItemGroup>

</Project>
