// <auto-generated />
using System;
using AFH.Booking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFH.Booking.Infrastructure.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20260820150000_AddPartnerWorkflowEndpoints")]
    partial class AddPartnerWorkflowEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("ApprovalRequestReferenceNumber", "dbo")
                .StartsAt(199L);

            modelBuilder.HasSequence("BookingReferenceNumber", "dbo")
                .StartsAt(1001L);

            modelBuilder.Entity("AFH.Booking.Domain.Bookings.LocationModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("AddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("City")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Postcode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("City", "Postcode");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.AdviserProfileProjectionModel", b =>
                {
                    b.Property<string>("AdviserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("CoverageRadiusMiles")
                        .HasColumnType("float");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HomePostcode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MailboxUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("MaxTravelTimeMinutes")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SkillsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AdviserId");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("IsActive", "Region");

                    b.ToTable("AdviserProfileProjections", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.AdviserSkillProjectionModel", b =>
                {
                    b.Property<string>("AdviserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SkillCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastSyncedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SkillLabel")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SourceVersion")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AdviserId", "SkillCode");

                    b.HasIndex("LastSyncedUtc");

                    b.HasIndex("AdviserId", "IsActive");

                    b.HasIndex("SkillCode", "IsActive");

                    b.ToTable("AdviserSkillProjections", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.ApplicationLogModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContextId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ExceptionMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PayloadJson")
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("UserId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("Category", "OccurredUtc");

                    b.HasIndex("Operation", "OccurredUtc");

                    b.ToTable("ApplicationLogs", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.ApprovalHistoryModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApprovalRequestId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Comments")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("ApprovalHistory", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.ApprovalRequestModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ApproverTargetDisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ApproverTargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ApproverTargetValue")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ExecutedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutionError")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReasonDetail")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Reference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestedPayloadJson")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("RequestedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reviewer")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasFilter("[Reference] IS NOT NULL");

                    b.HasIndex("TransactionId");

                    b.HasIndex("Status", "RequestedUtc");

                    b.ToTable("ApprovalRequests", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.ApprovalRequestReferenceAllocationModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.ApprovalRequestReferenceNumber");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("ApprovalRequestReferenceAllocations", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingHoldModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CalendarProviderEventId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("CancelledUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("HoldExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("ReleasedUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SlotId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HoldExpiresUtc");

                    b.HasIndex("Reference")
                        .IsUnique()
                        .HasFilter("[Reference] IS NOT NULL");

                    b.HasIndex("SlotId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SlotId", "Status");

                    b.ToTable("BookingHolds", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleChannelModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "Channel")
                        .IsUnique();

                    b.ToTable("BookingNotificationRuleChannels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("728736f1-89e2-4315-bab4-4670b526a201"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            TemplateKey = "booking-confirmed",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77fe97da-c2c5-44fb-8394-67e2f89d04b7"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            TemplateKey = "booking-rescheduled",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9cb40ca9-95c0-4fd2-9d87-51e711164a7b"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            TemplateKey = "booking-cancelled",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04eec961-a8f0-4cc9-bec7-d5c28c3356af"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            TemplateKey = "booking-hold",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("14179cdb-d3a0-4142-80a0-387403fd9201"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            TemplateKey = "adviser-request-submitted",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9beec961-a8f0-4cc9-bec7-d5c28c3357af"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            TemplateKey = "adviser-request-outcome",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6e093647-7ca9-4f98-9110-352533da95ef"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            TemplateKey = "booking-confirmed-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d5a7d12e-d0a9-40a3-8911-841cd5753c1e"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            TemplateKey = "booking-rescheduled-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2b3e321-e4e0-4223-a840-b262bfe6ef41"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            TemplateKey = "booking-cancelled-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa463227-5113-4c56-881e-07d47085c18e"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            TemplateKey = "booking-hold-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6af1c6ad-c7c2-4d98-8859-c36f9f4d9202"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            TemplateKey = "adviser-request-submitted-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9beec961-a8f0-4cc9-bec7-d5c28c3333bf"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            TemplateKey = "adviser-request-outcome-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceApplication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceApplication", "NotificationType")
                        .IsUnique();

                    b.ToTable("BookingNotificationRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingConfirmed",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingRescheduled",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingCancelled",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            NotificationType = "BookingHoldCreated",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "AdviserRequestSubmitted",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "AdviserRequestOutcome",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleRecipientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "RecipientType")
                        .IsUnique();

                    b.ToTable("BookingNotificationRuleRecipients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3096f1b-fd20-4cc3-a431-22f1d1021d01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("12d8a812-96fc-4020-93cd-30a82efa3c02"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f7c2b57-2d84-4d52-b9d0-00f1c9ccde01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f7726ed6-0939-49d3-b18c-5f2e34959f03"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("982657c1-2041-4fed-9cb1-5a802e258704"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("42cda070-c4cd-4fdb-ab79-c3d6870baf7e"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10f4906d-1d29-41de-8baa-aecf96c5de02"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55f92361-2f74-4128-a794-703eff8ca9e3"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a689b522-d031-44db-b145-e8109350c271"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("566301d9-a5d6-4e2d-a688-65b6d11c00f2"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9224f2f1-8408-423e-a318-cb3dd69fde03"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("27650cba-e5cf-4777-903d-24123832d1a3"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9c987676-c344-476a-a57a-8a22e2d97922"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Client",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6bc808c6-53a3-473f-972d-d8871678e4d4"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Adviser",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d39f9f03-df6f-4a1e-b7cb-dc94b2ddde04"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Manager",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("84186f63-a40d-419b-933d-573106880aeb"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7809ff7d-0721-430f-9b62-0ffb57dc9401"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20aaf403-b3d1-4247-b6d6-885eaf8b9402"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f8495119-62a9-45ee-9bf0-ae099ada9403"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f1e20620-c6b2-4871-b79f-ef9d23509404"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e5cd76c9-dc76-4a92-9686-f152b3d4c901"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9f053bd8-906f-4f48-8d22-cac5590afccb"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("358ac452-b5ad-4373-a593-1ff936e83298"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8b951db9-b91e-443f-9715-55df020b0b4b"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingReferenceAllocationModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Value")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("NEXT VALUE FOR dbo.BookingReferenceNumber");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.ToTable("BookingReferenceAllocations", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingSlotModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AdviserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AdviserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("CompanyBufferMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<double?>("DestinationLatitude")
                        .HasColumnType("float");

                    b.Property<string>("DestinationLocationRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("DestinationLongitude")
                        .HasColumnType("float");

                    b.Property<string>("DestinationPostcode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<decimal?>("DistanceMiles")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("LocationRef")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ProjectContext")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasDefaultValue("Booking");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("ScoreBreakdownJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<double?>("SourceLatitude")
                        .HasColumnType("float");

                    b.Property<string>("SourceLocationRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("SourceLongitude")
                        .HasColumnType("float");

                    b.Property<string>("SourcePostcode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("TravelCalculatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TravelConfidence")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("TravelDistanceMiles")
                        .HasColumnType("float");

                    b.Property<string>("TravelMessage")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int?>("TravelMinutes")
                        .HasColumnType("int");

                    b.Property<string>("TravelProvider")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TravelStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId");

                    b.HasIndex("TransactionId", "StartUtc");

                    b.ToTable("BookingSlots", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingTransactionModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("BookingReference")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ClientAddressLine1")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientAddressLine2")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientCounty")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ClientPostcode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ClientTown")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("bit");

                    b.Property<string>("LocationRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("MeetingType")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ProposedStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BookingReference")
                        .IsUnique()
                        .HasFilter("[BookingReference] IS NOT NULL");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("TransactionRef");

                    b.ToTable("BookingTransactions", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.DownstreamUpdateModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PartnerKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResponseReceivedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PartnerKey");

                    b.HasIndex("Status", "CreatedUtc");

                    b.ToTable("DownstreamUpdates", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.DuplicateClientCaseModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DuplicateTransactionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PrimaryTransactionRef")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("RaisedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("RaisedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resolution")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RaisedUtc");

                    b.ToTable("DuplicateClientCases", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.FeatureFlagModel", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("FeatureFlags", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.IntegrationOperationAuditModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IntegrationOperationAudits");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.IntegrationSyncStateModel", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("UpdatedUtc");

                    b.ToTable("IntegrationSyncStates", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.LifecycleEventModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActorId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AfterJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("BeforeJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("NewState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("OccurredUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartnerName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PreviousState")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ReasonNotes")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("RelatedBookingId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TriggerReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("EventType");

                    b.HasIndex("NewState");

                    b.HasIndex("OccurredUtc");

                    b.HasIndex("PartnerName");

                    b.HasIndex("TransactionId");

                    b.HasIndex("TriggerReason");

                    b.ToTable("LifecycleEvents", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.LifecycleStepModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ErrorDetails")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LifecycleEventId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LifecycleEventId");

                    b.HasIndex("LifecycleEventId", "Sequence")
                        .IsUnique();

                    b.ToTable("LifecycleSteps", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.MeetingTopicModel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("MeetingTopics", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.MeetingTypeModel", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DefaultDurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.HasIndex("IsActive", "SortOrder");

                    b.ToTable("MeetingTypes", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.OperationalIssueModel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("AdviserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BookingId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("DetectedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalationCount")
                        .HasColumnType("int");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastEscalatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId", "Code", "DetectedUtc");

                    b.HasIndex("ProviderEventId", "Code", "DetectedUtc");

                    b.ToTable("OperationalIssues", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.PartnerWorkflowEndpointModel", b =>
                {
                    b.Property<string>("PartnerKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ApiKeyHeaderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("BookingUpdatesPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("BookingUpdatesUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("IdempotencyKeyHeaderName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PayloadFormat")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("PartnerKey");

                    b.ToTable("PartnerWorkflowEndpoints", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.PartnerWorkflowRuleModel", b =>
                {
                    b.Property<string>("ChangeType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PartnerKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("ChangeType", "PartnerKey");

                    b.HasIndex("PartnerKey");

                    b.ToTable("PartnerWorkflowRules", (string)null);
                });

            modelBuilder.Entity("AFH.Common.Errors.EntityFramework.Entities.ErrorRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContextJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Method")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("OccurredUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Operation")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Path")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("OccurredUtc");

                    b.ToTable("ErrorRecordEntity", (string)null);
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingHoldModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.BookingSlotModel", "Slot")
                        .WithOne("Hold")
                        .HasForeignKey("AFH.Booking.Infrastructure.Persistence.Models.BookingHoldModel", "SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleChannelModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleModel", "Rule")
                        .WithMany("Channels")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleRecipientModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleModel", "Rule")
                        .WithMany("Recipients")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingSlotModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.BookingTransactionModel", "Transaction")
                        .WithMany("Slots")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.LifecycleStepModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.LifecycleEventModel", "LifecycleEvent")
                        .WithMany("Steps")
                        .HasForeignKey("LifecycleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LifecycleEvent");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.PartnerWorkflowRuleModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.PartnerWorkflowEndpointModel", "Endpoint")
                        .WithMany()
                        .HasForeignKey("PartnerKey")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingNotificationRuleModel", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Recipients");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingSlotModel", b =>
                {
                    b.Navigation("Hold");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.BookingTransactionModel", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.LifecycleEventModel", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
