<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AzureFunctionsVersion>V4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<_FunctionsBuildEnabled>false</_FunctionsBuildEnabled>
	</PropertyGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.51.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="3.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.50.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.3.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.1.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" />
		
		
		<PackageReference Include="Serilog" Version="4.3.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
		<PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\AFH.Acs.Domain\AFH.Acs.Domain.csproj" />
		<ProjectReference Include="..\AFH.Acs.Contract\AFH.Acs.Contract.csproj" />
		<ProjectReference Include="..\AFH.Acs.Application\AFH.Acs.Application.csproj" />
		<ProjectReference Include="..\AFH.Acs.Infrastructure\AFH.Acs.Infrastructure.csproj" />
		<ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors\AFH.Common.Errors.csproj" />
		<ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors.AzureFunctions\AFH.Common.Errors.AzureFunctions.csproj" />
		<ProjectReference Include="..\..\..\..\sdk\afh-common-error\src\AFH.Common.Errors.Email\AFH.Common.Errors.Email.csproj" />
		<ProjectReference Include="..\..\..\..\sdk\afh-common-speechai\src\AFH.Common.SpeechAI\AFH.Common.SpeechAI.csproj" />
	</ItemGroup>
</Project>
