// <auto-generated />
using System;
using AFH.Booking.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFH.Booking.Infrastructure.Migrations.NotificationPolicy
{
    [DbContext(typeof(NotificationPolicyDbContext))]
    [Migration("20260820144024_AddNotificationPolicyTables")]
    partial class AddNotificationPolicyTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleChannelModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateKey")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TemplateVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "Channel")
                        .IsUnique();

                    b.ToTable("NotificationRuleChannels", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("728736f1-89e2-4315-bab4-4670b526a201"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            TemplateKey = "booking-confirmed",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("77fe97da-c2c5-44fb-8394-67e2f89d04b7"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            TemplateKey = "booking-rescheduled",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9cb40ca9-95c0-4fd2-9d87-51e711164a7b"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            TemplateKey = "booking-cancelled",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("04eec961-a8f0-4cc9-bec7-d5c28c3356af"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            TemplateKey = "booking-hold",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("14179cdb-d3a0-4142-80a0-387403fd9201"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            TemplateKey = "adviser-request-submitted",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9beec961-a8f0-4cc9-bec7-d5c28c3357af"),
                            Channel = "Email",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            TemplateKey = "adviser-request-outcome",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6e093647-7ca9-4f98-9110-352533da95ef"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            TemplateKey = "booking-confirmed-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d5a7d12e-d0a9-40a3-8911-841cd5753c1e"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            TemplateKey = "booking-rescheduled-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2b3e321-e4e0-4223-a840-b262bfe6ef41"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            TemplateKey = "booking-cancelled-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa463227-5113-4c56-881e-07d47085c18e"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            TemplateKey = "booking-hold-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6af1c6ad-c7c2-4d98-8859-c36f9f4d9202"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            TemplateKey = "adviser-request-submitted-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9beec961-a8f0-4cc9-bec7-d5c28c3333bf"),
                            Channel = "Sms",
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            TemplateKey = "adviser-request-outcome-sms",
                            TemplateVersion = "v1",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceApplication")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceApplication", "NotificationType")
                        .IsUnique();

                    b.ToTable("NotificationRules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingConfirmed",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingRescheduled",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "BookingCancelled",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            NotificationType = "BookingHoldCreated",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "AdviserRequestSubmitted",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            NotificationType = "AdviserRequestOutcome",
                            SourceApplication = "Booking",
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleRecipientModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("RecipientType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RuleId", "RecipientType")
                        .IsUnique();

                    b.ToTable("NotificationRuleRecipients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f3096f1b-fd20-4cc3-a431-22f1d1021d01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("12d8a812-96fc-4020-93cd-30a82efa3c02"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8f7c2b57-2d84-4d52-b9d0-00f1c9ccde01"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f7726ed6-0939-49d3-b18c-5f2e34959f03"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("4a6f3c68-4eb7-4788-bd13-6908b33c7951"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("982657c1-2041-4fed-9cb1-5a802e258704"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("42cda070-c4cd-4fdb-ab79-c3d6870baf7e"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("10f4906d-1d29-41de-8baa-aecf96c5de02"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55f92361-2f74-4128-a794-703eff8ca9e3"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("7f6c8f21-9d36-481e-b5ad-08454d0036a6"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a689b522-d031-44db-b145-e8109350c271"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("566301d9-a5d6-4e2d-a688-65b6d11c00f2"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9224f2f1-8408-423e-a318-cb3dd69fde03"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("27650cba-e5cf-4777-903d-24123832d1a3"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("f6096d32-d3c7-49d4-8d16-9b7135e66274"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9c987676-c344-476a-a57a-8a22e2d97922"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Client",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("6bc808c6-53a3-473f-972d-d8871678e4d4"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Adviser",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d39f9f03-df6f-4a1e-b7cb-dc94b2ddde04"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "Manager",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("84186f63-a40d-419b-933d-573106880aeb"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = false,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("4e428654-c797-4f91-97fa-bd7b5086395a"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7809ff7d-0721-430f-9b62-0ffb57dc9401"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("20aaf403-b3d1-4247-b6d6-885eaf8b9402"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f8495119-62a9-45ee-9bf0-ae099ada9403"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f1e20620-c6b2-4871-b79f-ef9d23509404"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("19c2f130-6649-42ed-82cb-95f0d8706d01"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e5cd76c9-dc76-4a92-9686-f152b3d4c901"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Client",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9f053bd8-906f-4f48-8d22-cac5590afccb"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Adviser",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("358ac452-b5ad-4373-a593-1ff936e83298"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "Manager",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8b951db9-b91e-443f-9715-55df020b0b4b"),
                            CreatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Enabled = true,
                            RecipientType = "ContactCentre",
                            RuleId = new Guid("9b9be0be-7633-4576-ba6d-24ef060a0e6d"),
                            UpdatedUtc = new DateTime(2026, 5, 28, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleChannelModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleModel", "Rule")
                        .WithMany("Channels")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleRecipientModel", b =>
                {
                    b.HasOne("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleModel", "Rule")
                        .WithMany("Recipients")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("AFH.Booking.Infrastructure.Persistence.Models.NotificationRuleModel", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
